name: bloomlist
description: BloomList - dashboard premium de productivite personnelle.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
